import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import AuthForm from '../../components/AuthForm';
import logo from '../../public/logo.svg';

const Auth: NextPage = () => {
  return (
    <div className="h-screen text-center flex items-center justify-center">
      <Head>
        <title>Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-5/6 lg:w-1/3">
        <Image src={logo} />
        <AuthForm />
      </div>
    </div>
  );
};

export default Auth;
