import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import AuthModal from '../../components/AuthModal';
import CreatePost from '../../components/CreatePost';
import ExploreHeader from '../../components/ExploreHeader';
import PostCard from '../../components/PostCard';

const Explore: NextPage = () => {
  const [posts, setPosts] = useState<PostType[]>([
    {
      commentCount: 24,
      imgName: 'theresa.png',
      name: 'Theresa Webb',
      text: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
      timestamp: '5mins ago',
      emoticon: '👋',
      edited: false
    },
    {
      commentCount: 24,
      imgName: 'marvin.png',
      name: 'Marvin McKinney',
      text: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit. Exercitation veniam consequat sunt nostrud amet.',
      timestamp: '8mins ago',
      emoticon: '😞',
      edited: true
    }
  ]);

  const [showModal, setShowModal] = useState(false);

  function onPostHandler() {
    setShowModal(true);
  }

  return (
    <div className="h-screen">
      {showModal && <AuthModal closeModal={() => setShowModal(false)} />}
      <Head>
        <title>Explore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-16 md:px-48 xl:px-96 pt-16">
        <ExploreHeader />
        <CreatePost onPostHandler={onPostHandler} />
        {posts.map((post) => (
          <PostCard key={post.timestamp} post={post} />
        ))}
      </div>
    </div>
  );
};

export default Explore;

export type PostType = {
  name: string;
  imgName: string;
  timestamp: string;
  text: string;
  commentCount: number;
  emoticon: string;
  edited: boolean;
};
